// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe6gW2dWMrgFkUM2RBMAVYKwk3nEW3pBQ',
    appId: '1:171763188147:web:b2a94d7e26ead2eb300bc6',
    messagingSenderId: '171763188147',
    projectId: 'sominword',
    authDomain: 'sominword.firebaseapp.com',
    storageBucket: 'sominword.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADymiSapRZRUUtgTPdbSLN6OsofuvuLzs',
    appId: '1:171763188147:android:4b163b4c7b8d986f300bc6',
    messagingSenderId: '171763188147',
    projectId: 'sominword',
    storageBucket: 'sominword.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADbRoeH1Gh2FiuCmjUquxRLVqfQLOhg-0',
    appId: '1:171763188147:ios:142f8b67da914ce2300bc6',
    messagingSenderId: '171763188147',
    projectId: 'sominword',
    storageBucket: 'sominword.firebasestorage.app',
    iosBundleId: 'com.example.sominword',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADbRoeH1Gh2FiuCmjUquxRLVqfQLOhg-0',
    appId: '1:171763188147:ios:142f8b67da914ce2300bc6',
    messagingSenderId: '171763188147',
    projectId: 'sominword',
    storageBucket: 'sominword.firebasestorage.app',
    iosBundleId: 'com.example.sominword',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe6gW2dWMrgFkUM2RBMAVYKwk3nEW3pBQ',
    appId: '1:171763188147:web:ed20e9931606d77b300bc6',
    messagingSenderId: '171763188147',
    projectId: 'sominword',
    authDomain: 'sominword.firebaseapp.com',
    storageBucket: 'sominword.firebasestorage.app',
  );
}
